In [30]:
import pandas as pd

In [31]:
import numpy as np

In [32]:
import matplotlib.pyplot as plt

In [33]:
df= pd.read_csv("/content/carprices.csv")

In [34]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [35]:
dummies=pd.get_dummies(df['Car Model'])

In [36]:
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [37]:
merged=pd.concat([df,dummies],axis='columns')

In [38]:
merged

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [39]:
final=merged.drop(['Car Model'],axis='columns')

In [40]:
y=final['Sell Price($)']

In [41]:
y


0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [58]:
X= final[['Mileage','Age(yrs)','Audi A5','BMW X5','Mercedez Benz C class','Sell Price($)']]

In [59]:
final.shape

(13, 6)

In [60]:
final.columns

Index(['Mileage', 'Sell Price($)', 'Age(yrs)', 'Audi A5', 'BMW X5',
       'Mercedez Benz C class'],
      dtype='object')

In [61]:
X

Mileage  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class  Sell Price($)
0     69000         6        0       1                      0          18000
1     35000         3        0       1                      0          34000
2     57000         5        0       1                      0          26100
3     22500         2        0       1                      0          40000
4     46000         4        0       1                      0          31500
5     59000         5        1       0                      0          29400
6     52000         5        1       0                      0          32000
7     72000         6        1       0                      0          19300
8     91000         8        1       0                      0          12000
9     67000         6        0       0                      1          22000
10    83000         7        0       0                      1          20000
11    79000         7        0       0                      1          21000
12    59000         5        0       0                      1          33000

In [62]:
#Dataset splitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.30,random_state=1)


In [63]:
#Train Model 
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train, y_train)

#predict
reg.predict(X_test)

array([26100., 40000., 31500., 20000.])

In [64]:
#best fit line
#plt.plot(X,reg.predict(X))

In [65]:
reg.coef_

array([ 6.28162937e-16, -3.30913075e-12, -1.29866224e-13,  3.75590198e-13,
       -2.45724029e-13,  1.00000000e+00])

In [66]:
reg.intercept_

-3.2741809263825417e-11

In [67]:
reg.score(X_test,y_test)

1.0

In [68]:
reg.predict([[72000,4,0,0,0,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1.])